services:
  appserver:
    # https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx.html
    build: ./
    container_name: "${PROJECT:-mocion}-appserver"
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    environment:
      - WEB_DOCUMENT_ROOT=/app/web
  db:
    container_name: "${PROJECT:-mocion}-db"
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-drupal10}
      - MYSQL_USER=${MYSQL_USER:-drupal10}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-drupal10}
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    command: --default-authentication-plugin=caching_sha2_password
