services:
  appserver:
    container_name: appserver
    image: nginx:latest
    volumes:
      - ./:/app
      - ./.docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    links:
      - php-fpm
  db:
    container_name: db
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=drupal10
      - MYSQL_USER=drupal10
      - MYSQL_PASSWORD=drupal10
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "${DB_HOST_PORT:-3306}:3306"
    command: --default-authentication-plugin=mysql_native_password
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    links:
      - db

