<?php

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function allis_preprocess_page(&$variables) {
  // Añade una clase personalizada a la página si es la página de inicio.
  if (\Drupal::service('path.matcher')->isFrontPage()) {
    $variables['attributes']['class'][] = 'allis-front-page';
  }
}

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
function allis_preprocess_node(&$variables) {
  // Añade una clase personalizada a los nodos de tipo "article".
  if ($variables['node']->bundle() == 'article') {
    $variables['attributes']['class'][] = 'allis-article';
  }
}
